// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plcomhyfjdsqzytahwis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsY29taHlmamRzcXp5dGFod2lzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODAwMjgsImV4cCI6MjA3MjM1NjAyOH0.9PZslUCkMMRoQDj8p3V0PIQ7xweeRZgWd3FtOrtGxkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});